### ISSUE TITLE
Uncaught TypeError: unrar.RarArchive is not a constructor

### ISSUE THREAD

**Issue by alice-em** [YuJianrong/node-unrar.js#1]
It looks like `dist/js/unrar` is missing a `unrar.RarArchive` method.

**Comment by YuJianrong** [comment]
Can you describe more details about the issue? You're trying to compile the project by yourself or use it by `npm install`?
Please write the detail reproduce steps so I can find what had happened in your case.

BTW, if you are trying to compile the project by yourself instead of use the compiled package from npm, your problem maybe caused by unsucces installation of the emscripten docker image, please paste every error message you gotten so I can locate the problem.

**Comment by alice-em** [comment]
In my app, I get the following error...

```
Uncaught TypeError: unrar.RarArchive is not a constructor
    at FileExtractor.Extractor.openArc (/Users/nitrogen/Documents/Git/Wonder-Reader/node_modules/node-unrar-js/dist/js/extractor.js:179)
    at FileExtractor.Extractor.getFileList (/Users/nitrogen/Documents/Git/Wonder-Reader/node_modules/node-unrar-js/dist/js/extractor.js:48)
    at rarExtractor (/Users/nitrogen/Documents/Git/Wonder-Reader/app/js/file.js:185)
    at fileRouter (/Users/nitrogen/Documents/Git/Wonder-Reader/app/js/file.js:154)
    at fileLoad (/Users/nitrogen/Documents/Git/Wonder-Reader/app/js/file.js:107)
    at Object.exports.loader (/Users/nitrogen/Documents/Git/Wonder-Reader/app/js/file.js:145)
    at HTMLAnchorElement.onclick (index.html:1)
```

There isn't a `.RarArchive` I found anywhere in the module besides in the case referenced, and when I try to compile it, I get `warning: unresolved symbol: getgrnam`.  Otherwise, I get a presumably successful compile, assuming that warning is just a warning.

And the code is as follows
```javascript
// fileName = rarfile.cbr | tempFolder = /path/to/temp/folder
extractor = unrar.createExtractorFromFile(fileName, tempFolder);
console.dir(extractor);
var list = extractor.getFileList();
console.dir(list);

extracted = extractor.extractAll();
console.log(extracted);
extracted[1].files = extracted[1].files.reverse();
extracted[1].files.forEach(function(file) {
  !file.fileHeader.flags.directory
    ? fs.appendFileSync(tempFolder, new Buffer(file.extract[1]))
    : mkdirp.sync(path.join(tempFolder, file.fileHeader.name));
});
```
`.cbr` is a rar compressed comic file, and for other packages, `.cbr` is read and extracted fine, but not in a `win32` environment.  I'm thinking I might need to make a copy of the file, renamed to `.rar`, and then extract that file.  The tests run just fine, both for the repo and the fork I made.

```
> node-unrar-js@0.8.1 test /Users/nitrogen/Documents/Git/node-unrar.js
> mocha dist/test/*.spec.js



  Data Test
    ✓ Archive Comment (300ms)
    ✓ Header encryption
    ✓ File encrypted with different passwords
    ✓ Header encryption with password (464ms)
    ✓ Extract Header encryption file (265ms)
    ✓ Extract File encrypted with different passwords (no password)
    ✓ Extract File encrypted with different passwords (one password) (154ms)
    ✓ Extract File encrypted with different passwords (multiple passwords) (319ms)
    ✓ Extract File with folders (190ms)

  File Test
    ✓ Archive Comment
    ✓ Header encryption with password (214ms)
    ✓ Extract File with folders (47ms)


  12 passing (2s)
```

**Comment by YuJianrong** [comment]
I had renamed a `rar` file to `cbr` extension and run the following code in the REPL of nodejs:
```javascript
unrar = require("node-unrar-js")
extractor = unrar.createExtractorFromFile("xx.cbr", ".")
a=extractor.getFileList()
```
Everything works fine. So I believe the `.cbr` file is supported too.

I'm curious why the callstack start from `HTMLAnchorElement.onclick`? You run the code from browser?

The warning message in compiling is fine, please ignore it.

And for `unrar.RarArchive`, it's exported by the commonjs module `unrar.js` which compiled by Emscripten, although you cannot find `RarArchive` in the source code, but the name will be generated by the module, you can try
```REPL
> u = require("./node_modules/node-unrar-js/dist/js/unrar.js")
> console.dir(u.RarArchive)
{ [Function: RarArchive] argCount: undefined }
```
to find the function in the `REPL` of nodejs.

So please check your environment, to find:
1. Which version of nodejs you are using, if the version is older than `6.10.3`, please upgrade the nodejs to a newer version.
2. If you're using browserify to use the module in browser, I think `createExtractorFromData` is the only function supported for extraction.

**Comment by alice-em** [comment]
I'm calling the`HTMLAnchorElement.onclick` through `electron`.

In my `electron` console, I get the following

```
console.dir(u)
  __defineGetter__:__defineGetter__()
  __defineSetter__:__defineSetter__()
  __lookupGetter__:__lookupGetter__()
  __lookupSetter__:__lookupSetter__()
  constructor:Object()
  hasOwnProperty:hasOwnProperty()
  isPrototypeOf:isPrototypeOf()
  propertyIsEnumerable:propertyIsEnumerable()
  toLocaleString:toLocaleString()
  toString:toString()
  valueOf:valueOf()
  get __proto__:__proto__()
  set __proto__:__proto__()
```

And `console.dir(u.RarArchive)` returns `undefined`.  I have `0.8.1` installed for `node-unrar-js`, and `node` is running `7.4.0`.

While using `node` repl, `console.dir(u.RarArchive)` returns `{ [Function: RarArchive] argCount: undefined }`, strangely enough

**Comment by alice-em** [comment]
So, I might've found a hacky solution...

After beautifying `unrar.js` I modified a few lines to force the module to interpret the environment as `node` instead of `web`, as indicated below...
```javascript
if (Module['ENVIRONMENT']) {
  if (Module['ENVIRONMENT'] === 'WEB') {
    ENVIRONMENT_IS_WEB = false;
    ENVIRONMENT_IS_NODE = true;
  } else if (Module['ENVIRONMENT'] === 'WORKER') {
    ENVIRONMENT_IS_WORKER = true;
  } else if (Module['ENVIRONMENT'] === 'NODE') {
    ENVIRONMENT_IS_NODE = true;
  } else if (Module['ENVIRONMENT'] === 'SHELL') {
    ENVIRONMENT_IS_SHELL = true;
  } else {
    throw new Error('The provided Module[\'ENVIRONMENT\'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.');
  }
} else {
  ENVIRONMENT_IS_WEB = false;
  ENVIRONMENT_IS_WORKER = typeof importScripts === 'function';
  ENVIRONMENT_IS_NODE = typeof process === 'object' && typeof require === 'function' && !ENVIRONMENT_IS_WORKER;
  ENVIRONMENT_IS_SHELL = !ENVIRONMENT_IS_WEB && !ENVIRONMENT_IS_NODE && !ENVIRONMENT_IS_WORKER;
}
```

I'll test it out in a few minutes, and hopefully it's the solution I need.

**Comment by alice-em** [comment]
It's been tested and confirmed to work with `electron` and possibly other browser based node environments.

**Comment by YuJianrong** [comment]
Good to hear your good news.
Sorry I have no electron experience and I had Googled the issue of Electron with Emscripten but find nothing.

**Comment by mmontag** [comment]
Hi @YuJianrong, i'm having this issue. Can you reopen?

I think this is happening because unrar.js has no `module.exports = ...`.  You need to pass the flag `-s MODULARIZE=1` to Emscripten when you build. It will add some module.export code to the file, and that fixed it for me.

**Comment by erssebaggala** [comment]
@YuJianrong  any update on this?

**Comment by nguyenhmtriet** [comment]
if you use this library for JavaScript framework such as Angular, ReactJS, VueJS. You need to add this line at the end of file unrar.js. Now I'm working on Angular 4 and it worked properly.

run();if(typeof module!=="undefined"){module["exports"]=Module}

**Comment by kefniark** [comment]
The issue is still there, thanks @nguyenhmtriet for your hack, works nicely 👍

**Comment by YuJianrong** [comment]
Browser is supported in v1.0.0. I think the electron should be OK now.

**Comment by alice-em** [comment]
Awesome, I'll test it out in my app when I have the time.  Thanks for working on this
