### ISSUE TITLE
Support for custom extracted filename

### ISSUE THREAD

**Issue by CasperVerswijvelt** [YuJianrong/node-unrar.js#10]
It would be very helpful  if there was a way to customize the name of the extracted file.

E.g. in my usecase I would append `.partial` to the extracted filename and when the extracting is finished I would remove that suffix. For a .rar file that contains 1 file, `videofile.mkv`, the library would extract to `videofile.mkv.partial` and like that it will not get picked up as 'complete' file by other software

**Comment by YuJianrong** [comment]
New option `filenameTransform` created in `v1.0.1` and release. Please check the test case https://github.com/YuJianrong/node-unrar.js/blob/master/src/test/ExtractorFile.spec.ts#L151 for more details.

**Comment by CasperVerswijvelt** [comment]
@YuJianrong Hey, thanks for your quick implementation!

Is it intentional that the fileheaders in the extract return value is the original name and not the name determined by the `filenameTransform` function?

**Comment by YuJianrong** [comment]
> Is it intentional that the fileheaders in the extract return value is the original name and not the name determined by the `filenameTransform` function?

Yes. The `FileHeader` is extracted directly from the archive, I think it's better to keep the original file name instead of the transformed one since it's some kind of static attribute of the archive.
