### ISSUE TITLE
Stream-based Extractor

### ISSUE THREAD

**Issue by sntran** [YuJianrong/node-unrar.js#164]
Currently, `ExtractorData` stores all data of the rar file in memory, and when `extract()` is called, each files inside are also kept in memory as `Uint8Array` `extraction` property.

This works fine for small rar file, but would run out of memory for big file.

Would you consider adding another Extractor that supports `ReadableStream`, both for the rar file, and the files inside it?

**Comment by YuJianrong** [comment]
It's hard since the Extractor is just a simple wrapper for the file writing API for unrarLib. So technically the unrarlib may not write the file sequentially is hard to rewrite to a streaming class.
