### ISSUE TITLE
Preserve order of uncompressed files

### ISSUE THREAD

**Issue by rishighan** [YuJianrong/node-unrar.js#21]
How can I ensure that the uncompressed files are in the exact order that they were inside the archive?

When I only want to extract the first file in the archive, I am getting different results each time. The file in question is a `cbr ` comic archive. I'm trying to extract just the first file, naively assuming that it is the cover.

What is the best approach to go about this?

**Comment by YuJianrong** [comment]
> How can I ensure that the uncompressed files are in the exact order that they were inside the archive?
> 
> When I only want to extract the first file in the archive, I am getting different results each time. The file in question is a `cbr ` comic archive. I'm trying to extract just the first file, naively assuming that it is the cover.
> 
> What is the best approach to go about this?

I believe the `.cbr` is just plain `Rar` files. Maybe you are reuse the same unrar instance to decompress the archive? 
And please note this part in document:
```
Memory Leak
Note: although the return value fileHeaders and files are iterators, they must be traversed to the end! Otherwise the C++ object for archive extraction will not be destructed and cause memory leak.
```
Please traverse all the files to the end, and decompress for the picked files only.

**Comment by rishighan** [comment]
What does using the same unrar instance imply? 

Roughly, this is what I do:

```typescript
console.info("Unrar initiating.");
		await fse.ensureDir(options.targetExtractionFolder, directoryOptions);
		console.info(`${options.targetExtractionFolder} was created.`);

		const extractor = await unrar.createExtractorFromData({
			data: fileBuffer,
		});
		const files = extractor.extract({});
		const extractedFiles = [...files.files];
		for (const file of extractedFiles) {
			console.info(`Attempting to write ${file.fileHeader.name}`);
			const fileBuffer = file.extraction;
			const fileName = explodePath(file.fileHeader.name).fileName;
			// resize image
			await resizeImage(
				fileBuffer,
				path.resolve(options.targetExtractionFolder + "/" + fileName),
				200
			);
		}
		// walk the newly created folder and return results
		return await walkFolder(options.targetExtractionFolder, [
			".jpg",
			".png",
			".jpeg",
		]);

```

**Comment by YuJianrong** [comment]
I changed your code a bit like this :

```Javascript
const unrar = require('..');
const fs = require('fs');

async function test() {
  console.info('Unrar initiating.');

  const fileBuffer = fs.readFileSync('../testFiles/FolderTest.rar');

  const extractor = await unrar.createExtractorFromData({
    data: fileBuffer,
    password: '1234',
  });

  const files = extractor.extract({});
  const extractedFiles = [...files.files];
  for (const file of extractedFiles) {
    console.info(`Attempting to write ${file.fileHeader.name}`);
  }
}

async function main() {
  for (let i = 0; i < 10; ++i) {
    await test();
  }
}

main();
```

To try the `testFiles/FolderTest.rar` in this repo multiple times and the output is in the same order:
```
Unrar initiating.
Attempting to write Folder1/Folder Space/long.txt
Attempting to write Folder1/Folder 中文/2中文.txt
Unrar initiating.
Attempting to write Folder1/Folder Space/long.txt
Attempting to write Folder1/Folder 中文/2中文.txt
Unrar initiating.
Attempting to write Folder1/Folder Space/long.txt
Attempting to write Folder1/Folder 中文/2中文.txt
Unrar initiating.
Attempting to write Folder1/Folder Space/long.txt
Attempting to write Folder1/Folder 中文/2中文.txt
Unrar initiating.
```
Do you have any short example to show the different order by multiple calls?

**Comment by rishighan** [comment]
Thanks for the example! I will give `testFiles/FolderTest.rar` a shot. 
I will test with a `.cbr` file and report back.

**Comment by rishighan** [comment]
@YuJianrong it did work, thank you for your help!

**Comment by rishighan** [comment]
@YuJianrong Really sorry to bump this issue, but what's a shorthand for extracting just the first file from the archive?

**Comment by rishighan** [comment]
This is a very common use case for comic book archives, where the first file in the archive is _most often_ a cover. Also re-opening, since preservation of order is a serious consideration for this use case.

**Comment by rishighan** [comment]
Thanks @YuJianrong 
Is `firstFile` a predicate? Or does this mean I have to know what the first file is called beforehand?

**Comment by YuJianrong** [comment]
> 

I'm not sure what you mean. But you can always extract only the files meet some requirements by this code:
```TypeScript
    const { files } = extractor.extract({
      files: (fileHeader) => /* true to extract the file and false to skip */
    });
```
For example, this code will extract all files ending with ".png":
```TypeScript
    const { files } = extractor.extract({
      files: (fileHeader) => name.endsWith('.png')
    });
```
So this code: 
```
const { files } = extractor.extract({
      files: () => {
        if (firstFile) {
          firstFile = false;
          return true;
        } else return false;
      },
    });
```
Will do the extraction for the first time the function `files` is called and skip afterwards.

**Comment by rishighan** [comment]
I think that I ran into my original problem with not getting the first file from the archive. I tried it with [this archive](https://docs.rishighan.com/f/545b1a99e24d4db18c69/)

I got this file `Norse Mythology III 001-002.jpg` which is really the third in the sorted order.

For my use case, I use the command line version (a node.js wrapper) of `calibre`. It is written in python, and just taking a cursory look at the code that is used to extract the cover (https://github.com/kovidgoyal/calibre/blob/7acaee07d0e25571e8372af6aef18282697f41bd/src/calibre/utils/unrar.py#L100) it seems like `calibre` _sorts_ the file list after extraction and then picks out the first one.

I was wondering if that is possible with `node-unrar`...

**Comment by YuJianrong** [comment]
> I was wondering if that is possible with `node-unrar`...

`node-unrar` is a low-level wrapper for unrarDLL so sorting will not be implemented (it works exactly followed the API of unrarDLL), but you can do a sorting after a call to `getFileList()` and extract the first file only:
```javascript
async function extractFirstFile() {
  const extractor = await unrar.createExtractorFromFile({ filepath: './a.cbr' });
  const filenameList = [...extractor.getFileList().fileHeaders].map(({ name }) => name).sort();
  const { files } = extractor.extract({ files: [filenameList[0]] });
  const extractList = [...files];
  console.log(extractList.map(({ fileHeader: { name } }) => name));
}

extractFirstFile();
```

**Comment by rishighan** [comment]
Thank you @YuJianrong. You are a legend.

I ended up with a natural sort with something like:

```typescript
const filenameList = [...extractor.getFileList().fileHeaders]
    .map((fileListItem) => {
        if (fileListItem.flags.directory === false) {
            return fileListItem.name;
        }
    })
    .sort((a, b) => a.toLowerCase().localeCompare(b.toLowerCase()));
```

I originally wanted to extract the cover (first image) and an `xml` file that contains metadata in the same extraction pass. I think I can do it by just adding a check in the code above for the `xml` filetype.
