### ISSUE TITLE
monitor progress

### ISSUE THREAD

**Issue by AidasPa** [YuJianrong/node-unrar.js#233]
Is there a way to monitor the progress of the extract?

**Comment by YuJianrong** [comment]
It's technically possible, you can try to rewrite the function `write` of `ExtractorFile` or `ExtractorData`, the last argument if the size of each call, so progress can be calculated from it.
But the extracting is not stoppable, so to get the progress you must put the extracting in another thread (worker) and post the progress information to the main thread(worker).
