### ISSUE TITLE
Iterator skips directory

### ISSUE THREAD

**Issue by honeo** [YuJianrong/node-unrar.js#24]
v1.0.3

The iterator output by extractor.extract() does not contain a directory.
It is included in the iterator output by extractor.getFileList().
(As of v0.8.1, it was included in all APIs.)

**Comment by YuJianrong** [comment]
> v1.0.3
> 
> The iterator output by extractor.extract() does not contain a directory. It is included in the iterator output by extractor.getFileList(). (As of v0.8.1, it was included in all APIs.)

Sorry the v1.0.3 is rewritten with iterators and the output will be different to v0.8.1. I have no good idea to add the directory back to `extract()` since the type `ArcFile<Uint8Array>` returned by `extract()` are for files only. Please use both two functions if you need the information of directories.

**Comment by YuJianrong** [comment]
> When I iterate through the iterator created from FileExtractor.extract(), it starts writing the file, but this fails if the path contains a non-existent directory.Therefore, since ver1, iterators created from getFileList() are used to get the list in advance, create the directory in advance, and then write the file.
> 
> Since I need to iterate twice based on Archive compared to before the major update, I was worried if the cost of storage and CPU would be more of a bottleneck than the coding effort. Maybe I don't need to worry about it because the information I need is already cached at the stage of creating Extractor?

The folders should be created by this package automatically. I found the code may not be working properly on Windows.
If you are using Windows please try to upgrade to v1.0.4 which path in Windows should be supported.

**Comment by honeo** [comment]
I've confirmed that Win10 & cmd & ver1.0.4 FileExtractor automatically creates a directory up to the file path!
(I thought this behavior was in line with the fs module specs)

I still have some questions about the processing cost and the fact that empty directories in the Archive are ignored, but the purpose of the Issue has been achieved, so I'd like to close this one. Thank you for your quick response.

**Comment by honeo** [comment]
I've confirmed that Win10 & cmd & ver1.0.4 FileExtractor automatically creates a directory up to the file path!
(I thought this behavior was in line with the fs module specs)

I still have some questions about the processing cost and the fact that empty directories in the Archive are ignored, but the purpose of the Issue has been achieved, so I'd like to close this one. Thank you for your quick response.
