### ISSUE TITLE
 Can you give a one that can be run on a mobile browser (wasm)?

### ISSUE THREAD

**Issue by freekoy** [YuJianrong/node-unrar.js#3]
rt

**Comment by YuJianrong** [comment]
I think it's working on Mobile Browser. What's the reason of your request on wasm? Performance?

**Comment by klesun** [comment]
Wow, cool, does it work in browser even though it's called `node-unrar.js`? I'd file a PR to add that info in README then, it would open so many use cases for this lib...

**Comment by klesun** [comment]
@YuJianrong would you consider accepting #8? It makes `npm run browserify` produce a working build for browser.

**Comment by YuJianrong** [comment]
Browser is supported in the latest release v1.0.0
Note: Only the api to load/extract from memory is supported in browser.
