### ISSUE TITLE
Case sensitivity setting when extracting specific file

### ISSUE THREAD

**Issue by rishighan** [YuJianrong/node-unrar.js#30]
Given this code to extract `ComicInfo.xml`, from an archive, it is known that the filename will always be `comicinfo.xml` but the case is not known in advance. 

```typescript
// Read the archive file into a typedArray
const fileBuffer = await fse
    .readFile(filePath)
    .catch((err) => console.error("Failed to read file", err));
const extractor = await unrar.createExtractorFromData({
    data: fileBuffer,
});

const list = extractor.getFileList();
const listArcHeader = list.arcHeader; // archive header
const fileHeaders = [...list.fileHeaders]; // load the file headers

const extracted = extractor.extract({
    files: ["ComicInfo.xml"]
});
const files = [...extracted.files]; //load the files
console.log("asdas", files[0]);
return files[0].extraction;

```

How do I modify the code to extract all variations of `comicinfo.xml` (for e.g.: `comicinfo.xml`, `ComicInfo.xml`, `comic_info.xml` ?) Is there a regular expression I can use to match any variation?

**Comment by YuJianrong** [comment]
@rishighan `files` can be a callback function to tell unrar Extractor if the file should be extracted, so you can do it in this way:
```Javascript
const extracted = extractor.extract({
  files: ({ name }) => name.toLowerCase() === 'comicinfo.xml',
});
```

**Comment by rishighan** [comment]
Thanks @YuJianrong ! That was it!
