### ISSUE TITLE
createExtractorFromFile undefined with Electron (Webpack)

### ISSUE THREAD

**Issue by Mudbill** [YuJianrong/node-unrar.js#31]
After digging for a while, I noticed the note at the bottom of your [Webpack](https://github.com/YuJianrong/node-unrar.js/tree/master/demo/web) guide you mention `createExtractorFromFile` is unavailable due to `fs` and `path` requirements. 

I wonder if you have any solution if I want to use this API in an Electron app that has Webpack. Here, both `fs` and `path` are available, so it should in theory work, unless I'm missing something?

I am by no means a pro when it comes to Webpack configuration so maybe it's not that complicated.

### Reproduction

I use the Electron Forge template to get started.
```bash
yarn create electron-app my-app --template=typescript-webpack
yarn add node-unrar-js
```
If I now just open the index.ts file and `import * as unrar from 'node-unrar-js'` followed by `console.log(unrar)`, it is now missing `createExtractorFromFile`. Is this fixable?

Note: using `--template=typescript` without Webpack works.

**Comment by YuJianrong** [comment]
Hi @Mudbill,

Unfortunately I didn't assume this package will be used with webpack for nodejs env (I assume it always be browser for webpack), so there is no easy way to use it in your case. The `ExtractorFile` is still exported but it's a bit tricky to use it in webpack+electron. The `wasm` binary cannot be loaded automatically in this case so you need to load it manually. Here is a short example of how to use it in webpack:

```TypeScript
import fs from 'fs';

import type { Extractor } from 'node-unrar-js/esm/js/Extractor';
import { ExtractorFile } from 'node-unrar-js/esm/js/ExtractorFile';
import { getUnrar } from 'node-unrar-js/esm/js/unrar.singleton';

const wasmBinary = fs.readFileSync(require.resolve('node-unrar-js/esm/js/unrar.wasm'));

export interface ExtractorFromFileOptions {
  filepath: string;
  targetPath?: string;
  password?: string;
  filenameTransform?: (filename: string) => string;
}

export async function createExtractorFromFile({
  filepath,
  targetPath = '',
  password = '',
  filenameTransform = (filename: string) => filename,
}: ExtractorFromFileOptions): Promise<Extractor> {
  const unrar = await getUnrar({wasmBinary});
  const extractor = new ExtractorFile(unrar, filepath, targetPath, password, filenameTransform);
  unrar.extractor = extractor;
  return extractor;
}


// How to use it:
const extractor = createExtractorFromFile({ filepath: './WithComment.rar' });

extractor.then(extractor => console.log(extractor.getFileList()));
```

**Comment by Mudbill** [comment]
Thank you, I was able to get it working! This case may be a little niche, but perhaps it'd be worth adding a note about it in a Readme somewhere, possibly in the Webpack one. Either way, great job! Feel free to close this issue.

**Comment by YuJianrong** [comment]
Thanks for your suggestion. I've pushed a new v1.06 with option `wasmBinary` in `createExtractorFromFile` to make it easier to used in Webpack/electron, please close this issue if it's verified.

**Comment by Mudbill** [comment]
I updated my code with your new option and it works. Just had to remember to update the import path to use `node-unrar-js/esm` since the main import is still undefined in that environment.

Cheers!
