### ISSUE TITLE
Z_DATA_ERROR

### ISSUE THREAD

**Issue by theunreal** [YuJianrong/node-unrar.js#35]
Hi, trying to unzip the a GZ file and I get the following error:

```
Error: incorrect header check
    at Zlib.zlibOnError [as onerror] (node:zlib:190:17) {
  errno: -3,
  code: 'Z_DATA_ERROR'
}
```

on my windows machine I'm unable to extract it without any issue.
Any idea?

**Comment by theunreal** [comment]
[pricefull7290058140886-039-202204080558 (1).gz](https://github.com/YuJianrong/node-unrar.js/files/8449928/pricefull7290058140886-039-202204080558.1.gz)
It happens only on the file above ^

**Comment by YuJianrong** [comment]
@theunreal This package can only be used on `rar` files, I'm not expert of `zlib` in nodejs. please ask this question in node related community or stackoverflow.
