### ISSUE TITLE
error:extractor.extract is not a function

### ISSUE THREAD

**Issue by leconehu** [YuJianrong/node-unrar.js#383]
const buf = Uint8Array.from(fs.readFileSync(zipFile)).buffer;
            const extractor =   unrar.createExtractorFromData({ data: buf });
          
          //  const list = extractor.getFileList();
          //  const listArcHeader = list.arcHeader; // archive header
           // const fileHeaders = [...list.fileHeaders]; // load the file headers
          
            const extracted = extractor.extract({ files: [zipTargetPath] });
            // extracted.arcHeader  : archive header
            const files = [...extracted.files]; //load the files

**Comment by YuJianrong** [comment]
`unrar.createExtractorFromData({ data: buf })` returns a promise, you should use `await` or `.then` to use it.

```javascript
// example
const extractor = await unrar.createExtractorFromData({ data: buf });
```
