### ISSUE TITLE
gbk Chinese filename Garbled err... in Nodejs16

### ISSUE THREAD

**Issue by gowy222** [YuJianrong/node-unrar.js#39]
is there anyway to set decode/encode 'UTF-8/GBK'?

**Comment by gowy222** [comment]
{

  name: 'test1/￾- +-+-.txt',

  flags: { encrypted: false, solid: false, directory: false },

  packSize: 2044,

  unpSize: 5256,

  crc: 1594825946,

  time: '2022-07-24T04:19:12.000',

  unpVer: '5.0',

  method: 'Normal',

  comment: ''

}

**Comment by YuJianrong** [comment]
Sorry it cannot be supported.
The OEM charset support is done by Windows API but `node-unrar.js` is based on the linux version of `unrardll` which OEM charset is not supported.

抱歉无法支持GBK/GB2312编码。
Unrar的本地（OEM）编码支持是由Windows API提供的，`node-unrar.js`是基于Linux版本的`unrardll`编译的，无法提供对本地（OEM）字符集的支持。
