### ISSUE TITLE
Unrar big files

### ISSUE THREAD

**Issue by ariran5** [YuJianrong/node-unrar.js#5]
Hi this is a very good package to work with ."rar", but it can't unpack the archive if it weighs more than 32 GB. My file weighs in at 6.5 GB when you unpack 58. WinRar on my windows handles well

[Link to file](http://data.nalog.ru/Public/Downloads/20191226/fias_xml.rar)

**Comment by YuJianrong** [comment]
Big file should is supported in v1.0.0.

**Comment by anilovr** [comment]
Hello. This was added? I'm trying to unrar a 75MB rarfile and doesn't work, but when I try to unrar a rarfile with a empty .txt file it works really nice.

**Comment by YuJianrong** [comment]
> 

75MB is not big. What's the error message on your code?
